### PR TITLE
Remove unnecessary docs and rename for clarify

### PR DESCRIPTION
**Pull request by mattfbacon**

### CODE REVIEW

**Comment by seadeef** [comment]
I'm not removing comments lmao and I specifically asked you to add more. People who don't know C++ or haven't physically seen the robot will have no idea how the code works.

**Comment by seadeef** [comment]
You can make your name changes but please don't remove the comments

**Comment by mattfbacon** [comment]
If the comment an X::y is "Y's the X", that's redundant.

**Comment by seadeef** [comment]
Then add some meaningful comments, literally no reason to remove documentation

**Pull request closed without merging**
